local class = require "class"

describe("Function tests", function()

    it("'class.is_class':", function()
        local classA = class("ClassA")
        assert.is_true(class.is_class(classA))
        assert.is_true(class.is_class(classA()))
        assert.is_false(class.is_class(1))
        assert.is_false(class.is_class("123"))
        assert.is_false(class.is_class(true))
        assert.is_false(class.is_class(nil))
        assert.is_false(class.is_class({}))
    end)

    it("'class.is_instance'", function()
        local classA = class("ClassA")
        local classB = class("ClassA", classA)
        assert.is_true(class.is_instance(classA()))
        assert.is_true(class.is_instance(classB()))
        assert.is_false(class.is_instance(classA))
        assert.is_false(class.is_instance(classB))
        assert.is_false(class.is_instance(1))
        assert.is_false(class.is_instance("123"))
        assert.is_false(class.is_instance(true))
        assert.is_false(class.is_instance(nil))
        assert.is_false(class.is_instance({}))
    end)
end)
